command_timeout=86400

format = """ $username@$hostname:$directory$git_branch\
$jobs\
$battery\
$time\
$status\
$line_break\
$character"""

[hostname]
ssh_only = false
format = "[$hostname]($style)"
disabled = false
style = "red"

[username]
show_always = true
format = "[$user]($style)"
style_user = "red"

[git_branch]
format=" [$symbol $branch::$remote_name]($style) "
symbol=">>"
always_show_remote = true
style="magenta"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncate_to_repo = true
style = "cyan"
home_symbol = "~"
read_only = " !"

[character]
success_symbol = "[ λ](cyan)"
error_symbol = "[!λ](red)"
vicmd_symbol = "[:λ](green)"

[cmd_duration]
style = "cyan"
