#!/bin/bash

DATE=$(date +"%Y-%m-%d %H:%M")
HOST=$(hostname)

notify-send "Initializing sync..."

cd $HOME/.dotfiles

git pull
if [ $? != 0 ]; then
    notify-send "Error pulling from remote"
    exit
fi

git add .
OUTPUT=$(git commit -m "update from $HOST on $DATE")
if [ $? != 0 ]; then
    notify-send "Did not commit any changes:" "\n$OUTPUT"
    exit
fi

OUTPUT=$(git push)
if [ $? != 0 ]; then
    notify-send "Error pushing to remote!" "\n$OUTPUT"
    exit
else
    notify-send "Dotfiles synced!" "\n$(git status)"
fi
