#!/bin/bash

GTK_THEME=Pop
ICON_THEME=Mint-Y-Teal

cp ~/.config/kitty/kitty-base.conf ~/.config/kitty/kitty.conf
cat ~/.config/kitty/gruvbox-material-light-medium.conf >> ~/.config/kitty/kitty.conf

pkill -SIGUSR1 kitty

# xfconf-query -c xsettings -p /Net/ThemeName -s "$GTK_THEME"
# xfconf-query -c xsettings -p /Net/IconThemeName -s "$ICON_THEME"

# sed -i 's/dark/light/' $HOME/.config/rofi/config.rasi

# cat $HOME/.config/polybar/colors-light > $HOME/.config/polybar/config
# cat $HOME/.config/polybar/bar >> $HOME/.config/polybar/config

# pkill polybar
# polybar main &
